language: php
dist: trusty
matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
before_script:
  - composer install --dev
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --extensions=php,pdt --report=summary --ignore=./vendor/* --standard=./phpcs.xml.dist ./
after_script:
  - php ./vendor/bin/coveralls -v
